consent_selectors = [
    '//*[contains(@class, \'chefcookie__button--settings\')]',
    '//*[contains(@class, \'chefcookie__button--accept\')]',
    '//*[contains(@class, \'cmplz-view-preferences\')]',
    '//*[contains(@class, \'cmplz-save-preferences\')]',
    '//*[contains(@class, \'cmplz-cookiebanner\')]',
    '//*[@id=\'cliModalClose\']',
    '//*[@id=\'cliModalClose\']',
    '//*[@id=\'ccc-close\']',
    '//*[@id=\'ccc-content\']',
    '//*[@id=\'ccc-close\']',
    '//*[@id=\'ccc-content\']',
    '//*[@id=\'cookiescript_wrapper\']',
    '//*[contains(@class, \'cookiescript_checkbox\')]',
    '//*[@id=\'cookiescript_wrapper\']',
    '//*[contains(@class, \'cookiesjsr-settings\')]',
    '//*[contains(@class, \'cwc-setting-button\')]',
    '//*[contains(@class, \'cwc-sdk-container\')]',
    '//*[contains(@class, \'didomi-components-button\')]',
    '//*[@id=\'ez-manage-settings\']',
    '//*[@id=\'ez-save-settings\']',
    '//*[@id=\'ez-manage-settings\']',
    '//*[@id=\'ez-save-settings\']',
    '//*[contains(@class, \'save-preference-btn-handler\')]',
    '//*[contains(@class, \'optanon-toggle-display\')]',
    '//*[contains(@class, \'osano-cm-manage\')]',
    '//*[contains(@class, \'osano-cm-save\')]',
    '//*[@id=\'ppms_cm_save-choices\']',
    '//*[@id=\'ppms_cm_save-choices\']',
    '//*[contains(@class, \'qc-cmp-save-and-exit\')]',
    '//*[contains(@class, \'qc-cmp-ui-container\')]',
    '//*[contains(@class, \'qc-cmp-cleanslate\')]',
    '//*[contains(@class, \'priv-save-btn\')]',
    '//*[contains(@class, \'bg-overlay\')]',
    '//*[contains(@class, \'truste_box_overlay\')]',
    '//*[contains(@class, \'save-button\')]',
    '//*[contains(@class, \'unic-purposes\')]',
    '//*[@id=\'uc-btn-more-info-banner\']',
    '//*[contains(@class, \'uc-save-settings-button\')]',
    '//*[@id=\'uc-btn-more-info-banner\']',
    '//button[contains(text(), \'Accept\')]',
    '//button[contains(text(), \'Accept all\')]',
    '//button[contains(text(), \'I agree\')]',
    '//button[contains(text(), \'I accept\')]',
    '//button[contains(text(), \'Agree\')]',
    '//a[contains(text(), \'Accept\')]',
    '//input[@value=\'Accept\']',
    '//button[contains(text(), \'Accepter\')]',
    '//button[contains(text(), "J\'accepte")]',
    '//button[contains(text(), \'Tout accepter\')]',
    '//button[contains(text(), \'Aceptar\')]',
    '//input[@value=\'Я согласен с этими правилами\']',
    '//button[contains(text(), \'Согласен\')]',
    '//button[contains(text(), \'Принимаю\')]',
    '//button[contains(text(), \'Принять\')]',
    '//input[contains(@value, \'согласен\')]',
]